<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="DataTest::testAdd" tests="4" failures="1" errors="0" skipped="0" time="0.017">
        <testcase name="testAdd with data set #0" time="0.004"/>
        <testcase name="testAdd with data set #1" time="0.004"/>
        <testcase name="testAdd with data set #2" time="0.004"/>
        <testcase name="testAdd with data set #3" time="0.005">
            <failure message="" type="PHPUnit_Framework_ExpectationFailedException">DataTest::testAdd with data set #3
                (1, 1, 3)
                Failed asserting that &lt;integer:2&gt; matches expected &lt;integer:3&gt;.

                C:\Documents and Settings\pepinsson\Mes documents\www\htdocs\phpUnit\DataTest.php:9
            </failure>
        </testcase>
    </testsuite>
</testsuites>
